export const basicFoods = [
  { name: '흰쌀밥', calories: 310, protein: 6, unit: '200g', createdBy: "system" },
  { name: '계란', calories: 78, protein: 6, unit: '1개', createdBy: "system" },
  { name: '소고기', calories: 250, protein: 26, unit: '100g', createdBy: "system" },
  { name: '돼지고기', calories: 242, protein: 27, unit: '100g', createdBy: "system" },
  { name: '닭가슴살', calories: 165, protein: 31, unit: '100g', createdBy: "system" },
  { name: '연어', calories: 206, protein: 22, unit: '100g', createdBy: "system" },
  { name: '참치 통조림', calories: 132, protein: 28, unit: '100g', createdBy: "system" },
  { name: '두부', calories: 76, protein: 8, unit: '100g', createdBy: "system" },
  { name: '우유', calories: 61, protein: 3, unit: '200ml', createdBy: "system" },
  { name: '그릭 요거트', calories: 97, protein: 10, unit: '100g', createdBy: "system" },
  { name: '현미밥', calories: 149, protein: 3, unit: '200g', createdBy: "system" },
  { name: '고구마', calories: 86, protein: 1.5, unit: '100g', createdBy: "system" },
  { name: '바나나', calories: 89, protein: 1, unit: '1개', createdBy: "system" },
  { name: '아몬드', calories: 579, protein: 21, unit: '100g', createdBy: "system" },
];