export const basicFoods = [
  { name: '흰쌀밥', calorie: 310, protein: 6, unit: '200g', createdBy: "system" },
  { name: '계란', calorie: 78, protein: 6, unit: '1개', createdBy: "system" },
  { name: '소고기', calorie: 250, protein: 26, unit: '100g', createdBy: "system" },
  { name: '돼지고기', calorie: 242, protein: 27, unit: '100g', createdBy: "system" },
  { name: '닭가슴살', calorie: 165, protein: 31, unit: '100g', createdBy: "system" },
  { name: '연어', calorie: 206, protein: 22, unit: '100g', createdBy: "system" },
  { name: '참치 통조림', calorie: 132, protein: 28, unit: '100g', createdBy: "system" },
  { name: '두부', calorie: 76, protein: 8, unit: '100g', createdBy: "system" },
  { name: '우유', calorie: 61, protein: 3, unit: '200ml', createdBy: "system" },
  { name: '그릭 요거트', calorie: 97, protein: 10, unit: '100g', createdBy: "system" },
  { name: '현미밥', calorie: 149, protein: 3, unit: '200g', createdBy: "system" },
  { name: '고구마', calorie: 86, protein: 1.5, unit: '100g', createdBy: "system" },
  { name: '바나나', calorie: 89, protein: 1, unit: '1개', createdBy: "system" },
  { name: '아몬드', calorie: 579, protein: 21, unit: '100g', createdBy: "system" },
];